name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'lab8/**'

jobs:
  lab8_testing:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install pytest

      - name: Run tests
        run: pytest lab8/tests
        env:
          PYTHONPATH: ./lab8
